const languages = {
  'af-ZA': { name: 'Afrikaans - South Africa' },
  'ar-AE': { name: 'Arabic - United Arab Emirates' },
  'ar-BH': { name: 'Arabic - Bahrain' },
  'ar-DZ': { name: 'Arabic - Algeria' },
  'ar-EG': { name: 'Arabic - Egypt' },
  'ar-IQ': { name: 'Arabic - Iraq' },
  'ar-JO': { name: 'Arabic - Jordan' },
  'ar-KW': { name: 'Arabic - Kuwait' },
  'ar-LB': { name: 'Arabic - Lebanon' },
  'ar-LY': { name: 'Arabic - Libya' },
  'ar-MA': { name: 'Arabic - Morocco' },
  'ar-OM': { name: 'Arabic - Oman' },
  'ar-QA': { name: 'Arabic - Qatar' },
  'ar-SA': { name: 'Arabic - Saudi Arabia' },
  'ar-SY': { name: 'Arabic - Syria' },
  'ar-TN': { name: 'Arabic - Tunisia' },
  'ar-YE': { name: 'Arabic - Yemen' },
  'az-AZ': { name: 'Azeri - Azerbaijan' },
  'be-BY': { name: 'Belarusian - Belarus' },
  'bg-BG': { name: 'Bulgarian - Bulgaria' },
  'bs-BA': { name: 'Bosnian - Bosnia and Herzegovina' },
  'ca-ES': { name: 'Catalan - Spain' },
  'cs-CZ': { name: 'Czech - Czech Republic' },
  'cy-GB': { name: 'Welsh - United Kingdom' },
  'da-DK': { name: 'Danish - Denmark' },
  'de-AT': { name: 'German - Austria' },
  'de-CH': { name: 'German - Switzerland' },
  'de-DE': { name: 'German - Germany' },
  'de-LI': { name: 'German - Liechtenstein' },
  'de-LU': { name: 'German - Luxembourg' },
  'dv-MV': { name: 'Divehi - Maldives' },
  'el-GR': { name: 'Greek - Greece' },
  'en-AU': { name: 'English - Australia' },
  'en-BZ': { name: 'English - Belize' },
  'en-CA': { name: 'English - Canada' },
  'en-CB': { name: 'English - Caribbean' },
  'en-GB': { name: 'English - United Kingdom' },
  'en-IE': { name: 'English - Ireland' },
  'en-JM': { name: 'English - Jamaica' },
  'en-NZ': { name: 'English - New Zealand' },
  'en-PH': { name: 'English - Republic of the Philippines' },
  'en-TT': { name: 'English - Trinidad and Tobago' },
  'en-US': { name: 'English - United States' },
  'en-ZA': { name: 'English - South Africa' },
  'en-ZW': { name: 'English - Zimbabwe' },
  'es-AR': { name: 'Spanish - Argentina' },
  'es-BO': { name: 'Spanish - Bolivia' },
  'es-CL': { name: 'Spanish - Chile' },
  'es-CO': { name: 'Spanish - Colombia' },
  'es-CR': { name: 'Spanish - Costa Rica' },
  'es-DO': { name: 'Spanish - Dominican Republic' },
  'es-EC': { name: 'Spanish - Ecuador' },
  'es-ES': { name: 'Spanish - Spain' },
  'es-GT': { name: 'Spanish - Guatemala' },
  'es-HN': { name: 'Spanish - Honduras' },
  'es-MX': { name: 'Spanish - Mexico' },
  'es-NI': { name: 'Spanish - Nicaragua' },
  'es-PA': { name: 'Spanish - Panama' },
  'es-PE': { name: 'Spanish - Peru' },
  'es-PR': { name: 'Spanish - Puerto Rico' },
  'es-PY': { name: 'Spanish - Paraguay' },
  'es-SV': { name: 'Spanish - El Salvador' },
  'es-UY': { name: 'Spanish - Uruguay' },
  'es-VE': { name: 'Spanish - Venezuela' },
  'et-EE': { name: 'Estonian - Estonia' },
  'eu-ES': { name: 'Basque - Spain' },
  'fa-IR': { name: 'Farsi - Iran' },
  'fi-FI': { name: 'Finnish - Finland' },
  'fo-FO': { name: 'Faroese - Faroe Islands' },
  'fr-BE': { name: 'French - Belgium' },
  'fr-CA': { name: 'French - Canada' },
  'fr-CH': { name: 'French - Switzerland' },
  'fr-FR': { name: 'French - France' },
  'fr-LU': { name: 'French - Luxembourg' },
  'fr-MC': { name: 'French - Principality of Monaco' },
  'gl-ES': { name: 'Galician - Spain' },
  'gu-IN': { name: 'Gujarati - India' },
  'he-IL': { name: 'Hebrew - Israel' },
  'hi-IN': { name: 'Hindi - India' },
  'hr-BA': { name: 'Croatian - Bosnia and Herzegovina' },
  'hr-HR': { name: 'Croatian - Croatia' },
  'hu-HU': { name: 'Hungarian - Hungary' },
  'hy-AM': { name: 'Armenian - Armenia' },
  'id-ID': { name: 'Indonesian - Indonesia' },
  'is-IS': { name: 'Icelandic - Iceland' },
  'it-CH': { name: 'Italian - Switzerland' },
  'it-IT': { name: 'Italian - Italy' },
  'ja-JP': { name: 'Japanese - Japan' },
  'ka-GE': { name: 'Georgian - Georgia' },
  'kk-KZ': { name: 'Kazakh - Kazakhstan' },
  'kn-IN': { name: 'Kannada - India' },
  'ko-KR': { name: 'Korean - Korea' },
  'ky-KG': { name: 'Kyrgyz - Kyrgyzstan' },
  'ky-KZ': { name: 'Kyrgyz - Kazakhstan' },
  'lt-LT': { name: 'Lithuanian - Lithuania' },
  'lv-LV': { name: 'Latvian - Latvia' },
  'mi-NZ': { name: 'Maori - New Zealand' },
  'mk-MK': { name: 'Macedonian - Former Yugoslav Republic of Macedonia' },
  'mn-MN': { name: 'Mongolian - Mongolia' },
  'mr-IN': { name: 'Marathi - India' },
  'ms-BN': { name: 'Malay - Brunei Darussalam' },
  'ms-MY': { name: 'Malay - Malaysia' },
  'mt-MT': { name: 'Maltese - Malta' },
  'nb-NO': { name: 'Norwegian (Bokmål) - Norway' },
  'nl-BE': { name: 'Dutch - Belgium' },
  'nl-NL': { name: 'Dutch - Netherlands' },
  'nn-NO': { name: 'Norwegian (Nynorsk) - Norway' },
  'ns-ZA': { name: 'Northern Sotho - South Africa' },
  'pa-IN': { name: 'Punjabi - India' },
  'pl-PL': { name: 'Polish - Poland' },
  'ps-AR': { name: 'Pashto - Afghanistan' },
  'pt-BR': { name: 'Portuguese - Brazil' },
  'pt-PT': { name: 'Portuguese - Portugal' },
  'qu-BO': { name: 'Quechua - Bolivia' },
  'qu-EC': { name: 'Quechua - Ecuador' },
  'qu-PE': { name: 'Quechua - Peru' },
  'ro-RO': { name: 'Romanian - Romania' },
  'ru-RU': { name: 'Russian - Russia' },
  'sa-IN': { name: 'Sanskrit - India' },
  'se-FI': { name: 'Sami - Finland' },
  'se-NO': { name: 'Sami - Norway' },
  'se-SE': { name: 'Sami - Sweden' },
  'sk-SK': { name: 'Slovak - Slovakia' },
  'sl-SI': { name: 'Slovenian - Slovenia' },
  'sq-AL': { name: 'Albanian - Albania' },
  'sr-BA': { name: 'Serbian - Bosnia and Herzegovina' },
  'sr-SP': { name: 'Serbian - Serbia' },
  'sv-FI': { name: 'Swedish - Finland' },
  'sv-SE': { name: 'Swedish - Sweden' },
  'sw-KE': { name: 'Swahili - Kenya' },
  'syr-SY': { name: 'Syriac - Syria' },
  'ta-IN': { name: 'Tamil - India' },
  'te-IN': { name: 'Telugu - India' },
  'th-TH': { name: 'Thai - Thailand' },
  'tl-PH': { name: 'Tagalog - Philippines' },
  'tn-ZA': { name: 'Tswana - South Africa' },
  'tr-TR': { name: 'Turkish - Turkey' },
  'tt-RU': { name: 'Tatar - Russia' },
  'uk-UA': { name: 'Ukrainian - Ukraine' },
  'ur-PK': { name: 'Urdu - Islamic Republic of Pakistan' },
  'uz-UZ': { name: 'Uzbek - Uzbekistan' },
  'vi-VN': { name: 'Vietnamese - Vietnam' },
  'xh-ZA': { name: 'Xhosa - South Africa' },
  // 'zh-CHS': { name: 'Chinese (Simplified)' },
  // 'zh-CHT': { name: 'Chinese (Traditional)' },
  'zh-CN': { name: 'Chinese - China' },
  'zh-HK': { name: 'Chinese - Hong Kong' },
  'zh-MO': { name: 'Chinese - Macau' },
  'zh-SG': { name: 'Chinese - Singapore' },
  'zh-TW': { name: 'Chinese - Taiwan' },
  'zu-ZA': { name: 'Zulu - South Africa' }
};

export default languages;
